package com.nhsbsa.finance.shared;

import java.util.ArrayList;
import java.util.List;

public class SharedData {
  public static String day;
  public static String month;
  public static String year;
  public static String allocateDay;
  public static String allocateMonth;
  public static String allocateYear;
  public static String childDay;
  public static String childMonth;
  public static String childYear;
  public static String returnDay;
  public static String returnMonth;
  public static String returnYear;
  public static String maritalDay;
  public static String maritalMonth;
  public static String maritalYear;
  public static String username;
  public static String title;
  public static String firstName;
  public static String lastName;
  public static String childFirstName;
  public static String childLastName;
  public static String child1FirstName;
  public static String child1LastName;
  public static String allocationFirstName;
  public static String allocationLastName;
  public static String jobTitle;
  public static String nino;
  public static String phoneNumber;
  public static String relationship;
  public static String emailAddress;
  public static String employerName;
  public static String sharedCheckBox;
  public static String sharedNHSRadioButton;
  public static String shared1995RadioButton;
  public static String sharedRadioButton;
  public static String eqPaymasterName;
  public static String eqPaymasterRef;
  public static String streetLineOne;
  public static String streetLineTwo;
  public static String town;
  public static String postCode;
  public static String country;
  public static String gender;
  public static String accountType;
  public static String accountHolderName;
  public static String accountNumber;
  public static String rollNumber;
  public static String sortCodeFirstField;
  public static String sortCodeSecondField;
  public static String sortCodeThirdField;
  public static String certNumber;
  public static String combinedLTA;
  public static String grossAnnualRate;
  public static List<String> fullName = new ArrayList<>();
}
